### ISSUE TITLE
missing blynk.jar

### ISSUE THREAD

**Issue by Herreropl** [woahbase/alpine-blynk#1]
In the newest build there is a problem with blynk.jar file. I have checked inside container and this file have size 9 bytes. The problem is original blynk github - the java8 version for the newest build is missing .

**Comment by lapnapra** [comment]
Hey, good catch. Thanks for that.

This breaks the daily builds, so going back to the 0.41.3 release for now. The newest release looks kinda weird to me tbh so keeping it back until they release a working version for java8. The new (actually old but should at least be working) image should be up in a bit.

**Comment by Herreropl** [comment]
Hi,

Now is working fine ;-)

Thank you very much,
Best regards,
Michael

pon., 25.03.2019, 17:59 użytkownik lapnapra <notifications@github.com>
napisał:

**Comment by lapnapra** [comment]
Forgot to mention here but last month I noticed they released the new update that has support for Java8 again so I reversed the change that had the `0.41.3` version hardcoded into the build. That means the images pushed since then will have the latest version available instead of the hardcode.

Closing this one for now, can reopen if there are anymore problems after pulling the latest.

**Comment by Allineer** [comment]
woahbase/alpine-blynk:latest

Error: Unable to access jarfile /opt/blynk/blynk.jar
