### ISSUE TITLE
Error: Unable to access jarfile /opt/blynk/blynk.jar

### ISSUE THREAD

**Issue by Allineer** [woahbase/alpine-blynk#2]
#1 still relevant for `woahbase/alpine-blynk:latest` :(

**Comment by lapnapra** [comment]
Hey, that *IS* odd. 

I checked the last few successful builds and the test (which actually is 
enabled only for `ARCH == x86_64`, aka `latest`) looks okay to me.

Can you check when the image you're using was built, from its metadata? Maybe then I can check the relevant build.
Otherwise, you can always try pulling the last pushed image and testing it.
